swagger: '2.0'
info:
  version: 1.0
  title: Blog Service API

consumes:
  - application/json
produces:
  - application/json

paths:
  /search/{id}:
    get:
      responses:
        '200':
          description: OK